export const offices = [
  'New York',
  'Los Angeles',
  'İstanbul',
  'Barcelona',
  'Chicago',
  'Dubai',
  'Paris',
  'Toronto',
  'Warsaw',
  'Karachi',
  'Moscow',
  'São Paulo',
  'Tokyo',
  'London',
  'Bogotá',
  'Sydney',
  'Mexico City',
  'Madrid',
  'Buenos Aires',
  'Shanghai',
  'Cairo',
  'Berlin',
  'Seoul',
  'Toronto',

]

export const positions = [
  'Frontend Developer',
  'Backend Developer',
  'UI/UX Designer',
  'Full Stack Developer',
  'Software Engineer',
  'Product Manager',
  'Systems Analyst',
  'Data Scientist',
  'Network Administrator',
  'Database Administrator',
  'Content Writer',
  'Software Tester',
  'Marketing Manager',
  'Mobile App Developer',
  'Product Owner',
  'Systems Engineer',
  'Marketing Specialist',

]

export const languages = [
  'English',
  'Türkçe',
  'İspanyolca',
  'Arabic',
  'French',
  'Korean',
  'Spanish',
  'Russian',
  'Polish',
  'Urdu',
  'Portuguese',
  'Japanese',
  'Chinese',
  'German',
]

export const countryes = [
  'İngiltere',
  'Amerika',
  'Türkiye',
  'İstanbul',
  'İspanya',
  'Dubai',
  'Birleşik Arap Emirlikleri',
  'Fransa',
  'Güney Kore',
  'İspanya',
  'Rusya',
  'Arjantin',
  'Shanghai',
  'Mexico City',
  'Kanada',
  'Polonya',
  'Pakistan',
  'Brezilya',
  'Japonya',
  'Kolombiya',
  'Avustralya',
  'Meksika',
  'Çin',
  'İspanya',
  'Mısır',
  'Almanya',

]
