export const offices = [
  'New York',
  'Los Angeles',
  'İstanbul',
  'Barcelona',
  'Chicago',
  'Dubai',
  'Paris',
  'Toronto',
  'Warsaw',
  'Karachi',
  'Moscow',
  'São Paulo',
  'Tokyo',
  'London',
  'Bogotá',
  'Sydney',
  'Mexico City',
  'Madrid',
  'Buenos Aires',
  'Shanghai',
  'Cairo',
  'Berlin',
  'Seoul',
  'Toronto',

]

export const positions = [
  'Frontend Developer',
  'Backend Developer',
  'UI/UX Designer',
  'Full Stack Developer',
  'Software Engineer',
  'Product Manager',
  'Systems Analyst',
  'Data Scientist',
  'Network Administrator',
  'Database Administrator',
  'Content Writer',
  'Software Tester',
  'Marketing Manager',
  'Mobile App Developer',
  'Product Owner',
  'Systems Engineer',
  'Marketing Specialist',

]
