import { createStore } from 'vuex'

export interface User {
  id: number
  name: string
  position: string
  office: string
  age: number
  gender: string
  startDate: string
  salary: number
}

const users: User[] = [
  {
    id: 1,
    name: 'John Doe',
    position: 'Frontend Developer',
    office: 'New York',
    age: 30,
    gender: 'Male',
    startDate: '2022-01-15',
    salary: 75000,
    status: true,
  },
  {
    id: 2,
    name: 'Jane Smith',
    position: 'Backend Developer',
    office: 'Los Angeles',
    age: 28,
    gender: 'Female',
    startDate: '2021-11-10',
    salary: 80000,
    status: false,
  },
  {
    id: 3,
    name: 'Alice Johnson',
    position: 'UI/UX Designer',
    office: 'San Francisco',
    age: 32,
    gender: 'Female',
    startDate: '2023-03-05',
    salary: 70000,
    status: true,
  },
  {
    id: 4,
    name: 'David Brown',
    position: 'Full Stack Developer',
    office: 'Chicago',
    age: 29,
    gender: 'Male',
    startDate: '2022-05-20',
    salary: 78000,
    status: false,
  },
  {
    id: 5,
    name: 'Sophia Wilson',
    position: 'Data Scientist',
    office: 'Boston',
    age: 31,
    gender: 'Female',
    startDate: '2022-09-10',
    salary: 90000,
    status: true,
  },
  {
    id: 6,
    name: 'Michael Lee',
    position: 'DevOps Engineer',
    office: 'Seattle',
    age: 35,
    gender: 'Male',
    startDate: '2021-07-03',
    salary: 82000,
    status: true,
  },
  {
    id: 7,
    name: 'Eva Martinez',
    position: 'Product Manager',
    office: 'Miami',
    age: 33,
    gender: 'Female',
    startDate: '2021-10-22',
    salary: 85000,
    status: true,
  },
  {
    id: 8,
    name: 'Chris Anderson',
    position: 'Software Engineer',
    office: 'Denver',
    age: 27,
    gender: 'Male',
    startDate: '2022-04-15',
    salary: 72000,
    status: false,
  },
  {
    id: 9,
    name: 'Olivia Taylor',
    position: 'QA Tester',
    office: 'Dallas',
    age: 26,
    gender: 'Female',
    startDate: '2023-01-08',
    salary: 68000,
    status: true,
  },
  {
    id: 10,
    name: 'Alexander Johnson',
    position: 'Database Administrator',
    office: 'Houston',
    age: 34,
    gender: 'Male',
    startDate: '2022-06-18',
    salary: 78000,
    status: false,
  },
  {
    id: 11,
    name: 'Sophie Wilson',
    position: 'Frontend Developer',
    office: 'San Diego',
    age: 29,
    gender: 'Female',
    startDate: '2023-03-10',
    salary: 72000,
    status: true,
  },
  {
    id: 12,
    name: 'Daniel Lee',
    position: 'Project Manager',
    office: 'Austin',
    age: 37,
    gender: 'Male',
    startDate: '2022-11-05',
    salary: 90000,
    status: true,
  },
  {
    id: 13,
    name: 'Emma Davis',
    position: 'Software Engineer',
    office: 'Phoenix',
    age: 26,
    gender: 'Female',
    startDate: '2022-09-23',
    salary: 75000,
    status: false,
  },
  {
    id: 14,
    name: 'William Harris',
    position: 'Data Analyst',
    office: 'Philadelphia',
    age: 30,
    gender: 'Male',
    startDate: '2022-07-14',
    salary: 70000,
    status: false,
  },
  {
    id: 15,
    name: 'Mia Rodriguez',
    position: 'UI/UX Designer',
    office: 'Atlanta',
    age: 28,
    gender: 'Female',
    startDate: '2023-01-30',
    salary: 82000,
    status: true,
  },
  {
    id: 16,
    name: 'Aiden Thomas',
    position: 'Backend Developer',
    office: 'Miami',
    age: 31,
    gender: 'Male',
    startDate: '2022-03-12',
    salary: 82000,
    status: false,
  },
  {
    id: 17,
    name: 'Olivia Johnson',
    position: 'QA Tester',
    office: 'San Francisco',
    age: 27,
    gender: 'Female',
    startDate: '2023-02-18',
    salary: 69000,
    status: true,
  },
  {
    id: 18,
    name: 'James Wilson',
    position: 'Full Stack Developer',
    office: 'Chicago',
    age: 33,
    gender: 'Male',
    startDate: '2021-10-08',
    salary: 78000,
    status: true,
  },
  {
    id: 19,
    name: 'Liam Martinez',
    position: 'Product Manager',
    office: 'Dallas',
    age: 35,
    gender: 'Male',
    startDate: '2022-08-25',
    salary: 90000,
    status: false,
  },
  {
    id: 20,
    name: 'Sophia Anderson',
    position: 'Frontend Developer',
    office: 'Boston',
    age: 28,
    gender: 'Female',
    startDate: '2023-04-02',
    salary: 72000,
  },
  {
    id: 21,
    name: 'Noah Thomas',
    position: 'DevOps Engineer',
    office: 'Seattle',
    age: 30,
    gender: 'Male',
    startDate: '2022-06-14',
    salary: 82000,
    status: false,
  },
  {
    id: 22,
    name: 'Ava Davis',
    position: 'Data Analyst',
    office: 'Houston',
    age: 29,
    gender: 'Female',
    startDate: '2022-11-10',
    salary: 70000,
    status: false,
  },
  {
    id: 23,
    name: 'Lucas Johnson',
    position: 'Full Stack Developer',
    office: 'Denver',
    age: 32,
    gender: 'Male',
    startDate: '2022-07-21',
    salary: 78000,
    status: true,
  },
  {
    id: 24,
    name: 'Luna Smith',
    position: 'UI/UX Designer',
    office: 'Philadelphia',
    age: 27,
    gender: 'Female',
    startDate: '2023-02-15',
    salary: 82000,
    status: true,
  },
  {
    id: 25,
    name: 'Henry Wilson',
    position: 'Backend Developer',
    office: 'San Diego',
    age: 30,
    gender: 'Male',
    startDate: '2023-03-30',
    salary: 75000,
    status: false,
  },
  {
    id: 26,
    name: 'Chloe Lee',
    position: 'Data Scientist',
    office: 'Chicago',
    age: 31,
    gender: 'Female',
    startDate: '2022-09-01',
    salary: 90000,
    status: false,
  },
  {
    id: 27,
    name: 'Mason Martinez',
    position: 'Software Engineer',
    office: 'Denver',
    age: 28,
    gender: 'Male',
    startDate: '2021-08-10',
    salary: 82000,
    status: true,

  },
  {
    id: 28,
    name: 'Oliver Johnson',
    position: 'QA Tester',
    office: 'San Francisco',
    age: 27,
    gender: 'Male',
    startDate: '2022-04-22',
    salary: 70000,
    status: false,
  },
  {
    id: 29,
    name: 'Aria Smith',
    position: 'Frontend Developer',
    office: 'Los Angeles',
    age: 29,
    gender: 'Female',
    startDate: '2023-01-14',
    salary: 72000,
    status: false,
  },
  {
    id: 30,
    name: 'Ethan Davis',
    position: 'Product Manager',
    office: 'Seattle',
    age: 34,
    gender: 'Male',
    startDate: '2022-03-08',
    salary: 85000,
    status: true,
  },
  {
    id: 31,
    name: 'Aiden Wilson',
    position: 'Full Stack Developer',
    office: 'Phoenix',
    age: 33,
    gender: 'Male',
    startDate: '2021-09-15',
    salary: 78000,
    status: true,
  },
  {
    id: 32,
    name: 'Mia Martinez',
    position: 'UI/UX Designer',
    office: 'Houston',
    age: 29,
    gender: 'Female',
    startDate: '2022-10-05',
    salary: 70000,
    status: true,
  },
  {
    id: 33,
    name: 'Oliver Smith',
    position: 'Backend Developer',
    office: 'Los Angeles',
    age: 31,
    gender: 'Male',
    startDate: '2023-02-20',
    salary: 82000,
    status: false,
  },
  {
    id: 34,
    name: 'Sophie Brown',
    position: 'Data Scientist',
    office: 'Chicago',
    age: 28,
    gender: 'Female',
    startDate: '2022-07-12',
    salary: 90000,
    status: false,
  },
  {
    id: 35,
    name: 'Ethan Taylor',
    position: 'DevOps Engineer',
    office: 'San Francisco',
    age: 30,
    gender: 'Male',
    startDate: '2021-11-20',
    salary: 82000,
    status: false,
  },
  {
    id: 36,
    name: 'Ava Miller',
    position: 'Product Manager',
    office: 'New York',
    age: 34,
    gender: 'Female',
    startDate: '2022-05-08',
    salary: 85000,
    status: true,
  },
  {
    id: 37,
    name: 'William Davis',
    position: 'Frontend Developer',
    office: 'Seattle',
    age: 29,
    gender: 'Male',
    startDate: '2023-03-28',
    salary: 72000,
    status: true,
  },
  {
    id: 38,
    name: 'Chloe Wilson',
    position: 'QA Tester',
    office: 'Miami',
    age: 27,
    gender: 'Female',
    startDate: '2022-05-01',
    salary: 70000,
    status: false,
  },
  {
    id: 39,
    name: 'Daniel Johnson',
    position: 'Full Stack Developer',
    office: 'Phoenix',
    age: 31,
    gender: 'Male',
    startDate: '2022-11-15',
    salary: 78000,
    status: true,
  },
  {
    id: 40,
    name: 'Ella Taylor',
    position: 'UI/UX Designer',
    office: 'San Diego',
    age: 28,
    gender: 'Female',
    startDate: '2021-12-10',
    salary: 82000,
    status: false,
  },
  {
    id: 41,
    name: 'Henry Smith',
    position: 'Software Engineer',
    office: 'Dallas',
    age: 33,
    gender: 'Male',
    startDate: '2022-08-28',
    salary: 85000,
    status: true,
  },
  {
    id: 42,
    name: 'Mia Davis',
    position: 'Frontend Developer',
    office: 'Los Angeles',
    age: 30,
    gender: 'Female',
    startDate: '2022-02-12',
    salary: 72000,
    status: true,
  },
]

export default createStore({
  state: {
    users,
  },
  mutations: {
    addUser(state, newUser) {
      state.users.push(newUser)
    },
    deleteUser(state, userId) {
      state.users = state.users.filter(user => user.id !== userId)
    },

    // kullanici bilgilerini duzenlemek
    updateUser(state, updatedUser) {
      const index = state.users.findIndex(user => user.id === updatedUser.id)
      if (index !== -1)
        state.users[index] = updatedUser
    },
    setFilterd(state) {
      if (state.filterCategory) {
        state.filteredProducts = state.products.filter(
          product => product.category === state.filterCategory,
        )
      }
      else {
        state.filteredProducts = state.products
      }
    },
  },
  actions: {
    addUserData({ commit }, newUser) {
      commit('addUser', newUser)
    },
    deleteUserData({ commit }, userId) {
      commit('deleteUser', userId)
    },
    toggleUserStatus({ commit }, user) {
      commit('updateUser', user)
    },
    getUser({ state }, userId) {
      // Kullanıcıyı kimliğine göre bul
      const user = state.users.find(user => user.id === userId)

      return Promise.resolve({ data: user })
    },

  },
  getters: {
    users: state => state.users,
  },
})
